export const technicalSkills = [
  { type: "skill_algo", max: 13 },
  { type: "skill_sys-admin", max: 8 },
  { type: "skill_front-end", max: 14 },
  { type: "skill_back-end", max: 19 },
  { type: "skill_stats", max: 2 },
  { type: "skill_ai", max: 12 },
  { type: "skill_game", max: 19 },
  { type: "skill_blockchain", max: 5 },
  { type: "skill_mobile", max: 7 },
  { type: "skill_tcp", max: 6 },
  { type: "skill_prog", max: 58 },
]
export const technologies = [
  { type: "skill_go", max: 22 },
  { type: "skill_js", max: 6 },
  { type: "skill_rust", max: 6 },
  { type: "skill_html", max: 8 },
  { type: "skill_css", max: 4 },
  { type: "skill_unix", max: 12 },
  { type: "skill_docker", max: 3 },
  { type: "skill_sql", max: 2 },
  { type: "skill_c", max: 1 },
  { type: "skill_sh", max: 3 },
  { type: "skill_php", max: 1 },
  { type: "skill_python", max: 1 },
  { type: "skill_ruby", max: 1 },
  { type: "skill_java", max: 0 },
  { type: "skill_c-sharp", max: 0 },
  { type: "skill_c-pp", max: 1 },
  { type: "skill_graphql", max: 1 },
  { type: "skill_rails", max: 1 },
  { type: "skill_laravel", max: 1 },
  { type: "skill_django", max: 1 },
  { type: "skill_react", max: 0 },
  { type: "skill_dotnet", max: 0 },
  { type: "skill_electron", max: 1 },
  { type: "skill_ux", max: 0 },
  { type: "skill_cloud", max: 0 },
  { type: "skill_automation", max: 0 },
  { type: "skill_cybersecurity", max: 9 },
  { type: "skill_ci", max: 0 },
  { type: "skill_no-sql", max: 0 },
  { type: "skill_git", max: 1 },
]
